# This file defines the build script for all supported aspnetcore images.
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the generator for testing later.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'generator', './dockerfile_generator' ]
  id: 'generator-build'
  waitFor: ['-']



  # .NET Core 3.1.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:3.1-${_TAG}',
          '--no-cache', '--pull', './versions/aspnetcore-3.1/image' ]
  id: 'aspnetcore-3-1-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:3.1-${_TAG}',
         '--config', '/workspace/versions/aspnetcore-3.1/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-3-1-test'
  waitFor: [ 'aspnetcore-3-1-build' ]
- name: generator
  args: [ './versions/aspnetcore-3.1/functional_tests/published', '${_DOCKER_NAMESPACE}/aspnetcore:3.1-${_TAG}' ]
  id: 'generator-run-3-1'
  waitFor: [ 'generator-build', 'aspnetcore-3-1-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-3-1', './versions/aspnetcore-3.1/functional_tests/published' ]
  id: 'test-app-build-3-1'
  waitFor: [ 'generator-run-3-1' ]
- name: test-app-3-1
  id: 'test-app-run-3-1'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 3.1!" ]]' ]
  waitFor: [ 'test-app-build-3-1' ]

  # Publish the images.
images:
  
  - '${_DOCKER_NAMESPACE}/aspnetcore:3.1-${_TAG}'
 
